INSERT INTO animal.animal (animal_type_id, gender_id, breed_id, size, age, color) VALUES (1, 2, 4, 'keskmine', 'täisvasvanud', 'Tume');
INSERT INTO animal.animal (animal_type_id, gender_id, breed_id, size, age, color) VALUES (2, 2, 8, 'suur', 'vana', 'Hall');
INSERT INTO animal.animal (animal_type_id, gender_id, breed_id, size, age, color) VALUES (3, 1, 9, 'väike', 'noor', 'Tume, kollaste täppidega');
INSERT INTO animal.animal (animal_type_id, gender_id, breed_id, size, age, color) VALUES (2, 1, 5, 'keskmine', 'noor', 'kirju');
INSERT INTO animal.animal (animal_type_id, gender_id, breed_id, size, age, color) VALUES (2, 1, 6, 'suur', 'vana', 'hele');
INSERT INTO animal.animal (animal_type_id, gender_id, breed_id, size, age, color) VALUES (2, 2, 7, 'väike', 'täisvasvanud', 'Kirju');
INSERT INTO animal.animal (animal_type_id, gender_id, breed_id, size, age, color) VALUES (1, 1, 1, 'väike', 'noor', 'Kuldne');
INSERT INTO animal.animal (animal_type_id, gender_id, breed_id, size, age, color) VALUES (3, 1, 9, 'väike', 'noor', 'tume');
INSERT INTO animal.animal (animal_type_id, gender_id, breed_id, size, age, color) VALUES (1, 1, 2, 'väike', 'täisvasvanud', 'Pruun');
INSERT INTO animal.animal (animal_type_id, gender_id, breed_id, size, age, color) VALUES (1, 1, 3, 'suur', 'vana', 'Valge pruuni kirju');
